# Generated by Django 6.0.7 on 2026-07-24 14:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HazardReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('hazard_type', models.CharField(choices=[('pothole', 'Pothole'), ('damaged_sign', 'Damaged Sign'), ('broken_light', 'Broken Street Light'), ('road_crack', 'Road Crack / Sinkhole'), ('flooding', 'Flooding / Standing Water'), ('debris', 'Debris on Road'), ('guardrail', 'Damaged Guardrail'), ('bridge_damage', 'Bridge Damage'), ('other', 'Other')], default='pothole', max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low — Minor inconvenience'), ('medium', 'Medium — Noticeable hazard'), ('high', 'High — Dangerous'), ('critical', 'Critical — Immediate danger')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('in_progress', 'In Progress'), ('pending_verify', 'Pending Verification'), ('resolved', 'Resolved'), ('fixed', 'Fixed')], default='open', max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS latitude (optional)', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS longitude (optional)', max_digits=9, null=True)),
                ('ai_score', models.IntegerField(default=0, help_text='AI severity score 1–10 (0 = not yet scored)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('document', models.FileField(blank=True, help_text='Optional supporting document (PDF, DOCX, etc.)', null=True, upload_to='documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hazard Report',
                'verbose_name_plural': 'Hazard Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reports.hazardreport')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity_score', models.IntegerField(default=0, help_text='AI-computed severity 1–10 (0 = stub / not yet computed)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('raw_response', models.JSONField(blank=True, default=dict, help_text='Full raw JSON response from the AI API')),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('is_duplicate_of', models.ForeignKey(blank=True, help_text='If set, this report is likely a duplicate of another report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='reports.hazardreport')),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insight', to='reports.hazardreport')),
            ],
            options={
                'verbose_name': 'AI Insight',
                'verbose_name_plural': 'AI Insights',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='reports.hazardreport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('citizen', 'Citizen'), ('city_admin', 'City Admin'), ('super_admin', 'Super Admin')], default='citizen', max_length=20)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('avatar', models.ImageField(blank=True, help_text='Profile picture (optional)', null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='ReportPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='report_photos/%Y/%m/')),
                ('caption', models.CharField(blank=True, default='', max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='reports.hazardreport')),
            ],
            options={
                'verbose_name': 'Report Photo',
                'verbose_name_plural': 'Report Photos',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('open', 'Open'), ('under_review', 'Under Review'), ('in_progress', 'In Progress'), ('pending_verify', 'Pending Verification'), ('resolved', 'Resolved'), ('fixed', 'Fixed')], default='', max_length=20)),
                ('new_status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('in_progress', 'In Progress'), ('pending_verify', 'Pending Verification'), ('resolved', 'Resolved'), ('fixed', 'Fixed')], max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True, default='', help_text='Official admin response or reason for this status change')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='reports.hazardreport')),
            ],
            options={
                'verbose_name': 'Status History',
                'verbose_name_plural': 'Status Histories',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Upvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', to='reports.hazardreport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Upvote',
                'verbose_name_plural': 'Upvotes',
                'unique_together': {('report', 'user')},
            },
        ),
    ]
